-- MySQL Script generated by MySQL Workbench
-- Tue Mar  6 20:26:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema m_ej2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema m_ej2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `m_ej2` DEFAULT CHARACTER SET utf8 ;
USE `m_ej2` ;

-- -----------------------------------------------------
-- Table `m_ej2`.`Entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Entidad` (
  `cod` INT NOT NULL,
  `domicilio` VARCHAR(60) NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Jueces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Jueces` (
  `clave` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `tiempoServicio` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`clave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Sucursal` (
  `entidad` INT NOT NULL,
  `domicilio` VARCHAR(60) NULL,
  `Cod` INT NOT NULL,
  PRIMARY KEY (`entidad`, `Cod`),
  INDEX `fk_Sucursal_Entidad_idx` (`Cod` ASC),
  CONSTRAINT `fk_Sucursal_Entidad`
    FOREIGN KEY (`Cod`)
    REFERENCES `m_ej2`.`Entidad` (`cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Principal` (
  `director` VARCHAR(60) NULL,
  `numempl` TINYINT UNSIGNED NULL,
  `idEntidad` INT NOT NULL,
  `idSucursal` INT NOT NULL,
  INDEX `fk_Principal_Sucursal1_idx` (`idEntidad` ASC, `idSucursal` ASC),
  PRIMARY KEY (`idSucursal`, `idEntidad`),
  CONSTRAINT `fk_Principal_Sucursal1`
    FOREIGN KEY (`idEntidad` , `idSucursal`)
    REFERENCES `m_ej2`.`Sucursal` (`entidad` , `Cod`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Secundaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Secundaria` (
  `idSucursal` INT NOT NULL,
  `idEntidad` INT NOT NULL,
  `idEntidadDepende` INT NOT NULL,
  `idSucursalDepende` INT NOT NULL,
  INDEX `fk_Secundaria_Sucursal1_idx` (`idSucursal` ASC, `idEntidad` ASC),
  PRIMARY KEY (`idEntidad`, `idSucursal`),
  INDEX `fk_Secundaria_Principal1_idx` (`idEntidadDepende` ASC, `idSucursalDepende` ASC),
  CONSTRAINT `fk_Secundaria_Sucursal1`
    FOREIGN KEY (`idSucursal` , `idEntidad`)
    REFERENCES `m_ej2`.`Sucursal` (`entidad` , `Cod`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Secundaria_Principal1`
    FOREIGN KEY (`idEntidadDepende` , `idSucursalDepende`)
    REFERENCES `m_ej2`.`Principal` (`idSucursal` , `idEntidad`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Atraco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Atraco` (
  `cod` INT NOT NULL,
  `fecha` DATE NULL,
  `dinero` DECIMAL(11,2) NULL,
  `tipoArmas` ENUM('Arma Blanca', 'Arma Fuego') NULL,
  `numVictimas` TINYINT UNSIGNED NULL,
  `idSucursal` INT NOT NULL,
  `idEntidad` INT NOT NULL,
  PRIMARY KEY (`cod`),
  INDEX `fk_Atraco_Sucursal1_idx` (`idSucursal` ASC, `idEntidad` ASC),
  CONSTRAINT `fk_Atraco_Sucursal1`
    FOREIGN KEY (`idSucursal` , `idEntidad`)
    REFERENCES `m_ej2`.`Sucursal` (`entidad` , `Cod`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Bandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Bandas` (
  `num` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Cabecilla` INT NOT NULL,
  PRIMARY KEY (`num`),
  INDEX `fk_Bandas_Persona1_idx` (`Cabecilla` ASC),
  UNIQUE INDEX `Persona_clave_UNIQUE` (`Cabecilla` ASC),
  CONSTRAINT `fk_Bandas_Persona1`
    FOREIGN KEY (`Cabecilla`)
    REFERENCES `m_ej2`.`Persona` (`clave`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Persona` (
  `clave` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `DNI` CHAR(9) NULL,
  `Bandas` INT NULL,
  PRIMARY KEY (`clave`),
  INDEX `fk_Persona_Bandas1_idx` (`Bandas` ASC),
  CONSTRAINT `fk_Persona_Bandas1`
    FOREIGN KEY (`Bandas`)
    REFERENCES `m_ej2`.`Bandas` (`num`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Participa` (
  `idPersona` INT NOT NULL,
  `idAtraco` INT NOT NULL,
  `condenado` TINYINT NULL,
  `tiempoCarcel` TINYINT NULL,
  `Juez` INT NOT NULL,
  PRIMARY KEY (`idPersona`, `idAtraco`),
  INDEX `fk_Persona_has_Atraco_Atraco1_idx` (`idAtraco` ASC),
  INDEX `fk_Persona_has_Atraco_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Participa_Jueces1_idx` (`Juez` ASC),
  CONSTRAINT `fk_Persona_has_Atraco_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `m_ej2`.`Persona` (`clave`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Persona_has_Atraco_Atraco1`
    FOREIGN KEY (`idAtraco`)
    REFERENCES `m_ej2`.`Atraco` (`cod`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Participa_Jueces1`
    FOREIGN KEY (`Juez`)
    REFERENCES `m_ej2`.`Jueces` (`clave`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Vigilantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Vigilantes` (
  `cod` INT NOT NULL,
  `nombre` VARCHAR(60) NULL,
  `fechanac` DATE NULL,
  PRIMARY KEY (`cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `m_ej2`.`Contratar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `m_ej2`.`Contratar` (
  `idSucursal` INT NOT NULL,
  `idEntidad` INT NOT NULL,
  `idVigilantes` INT NOT NULL,
  `ffin` DATE NULL,
  `fini` DATE NULL,
  `arma` VARCHAR(45) NULL,
  PRIMARY KEY (`idSucursal`, `idEntidad`, `idVigilantes`),
  INDEX `fk_Sucursal_has_Vigilantes_Vigilantes1_idx` (`idVigilantes` ASC),
  INDEX `fk_Sucursal_has_Vigilantes_Sucursal1_idx` (`idSucursal` ASC, `idEntidad` ASC),
  CONSTRAINT `fk_Sucursal_has_Vigilantes_Sucursal1`
    FOREIGN KEY (`idSucursal` , `idEntidad`)
    REFERENCES `m_ej2`.`Sucursal` (`entidad` , `Cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sucursal_has_Vigilantes_Vigilantes1`
    FOREIGN KEY (`idVigilantes`)
    REFERENCES `m_ej2`.`Vigilantes` (`cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
